ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root

COPY --chown=anlapi:anlapi backend/bin/anlapi-linux-amd64 /app/anlapi
COPY --chown=anlapi:anlapi backend/resources /app/resources

RUN chmod 0755 /app/anlapi
